### ISSUE TITLE
some snippets don't work

### ISSUE THREAD

**Issue by hughkli** [QMUI/QMUI_iOS_CodeSnippets#1]
_pa_ and _pc_ don't work in interface declaration area of a _.m_ file.
<img width="301" alt="2016-09-18 17 14 13" src="https://cloud.githubusercontent.com/assets/15059475/18614575/5725bdec-7dc3-11e6-92e5-21fcda1c5e40.png">

**Comment by citynight** [comment]
![image](https://cloud.githubusercontent.com/assets/7713239/19303316/ba977034-909a-11e6-88f7-149b13d85550.png)
更改成all 就好了

**Comment by MoLice** [comment]
@Mekor 是的，前阵子我们已经把有可能出问题的一些 `Code Snippet` 的作用域改为 `All` 了，可以更新一下，不用本地修改
