### ISSUE TITLE
希望代码格式方面能和系统对齐

### ISSUE THREAD

**Issue by yingkong1987** [QMUI/QMUI_iOS_CodeSnippets#2]
比如 property 和 ( 中间会有一个空格. 

这个snippet确实很实用.感谢作者开源分享出来.

**Comment by MoLice** [comment]
关于代码格式的问题，我们团队内部也讨论过，主要是苹果官方对这种细节并没有明确的标准可以参考，包括 UIKit 自身在空格的使用方面也掺杂着各种不同的写法，你可以看 iOS 10.2 里，UIView.h 里的 `layer` 属性 和 `focused` 属性就是用不同的空格写法。
因此我们最终统一选择目前这种 property 和 ( 之间无空格的写法。

**Comment by yingkong1987** [comment]
受益匪浅,感谢大神百忙之中回复问题,还给了一些示例.

**Comment by JxJPu9bD** [comment]
> 关于代码格式的问题，我们团队内部也讨论过，主要是苹果官方对这种细节并没有明确的标准可以参考，包括 UIKit 自身在空格的使用方面也掺杂着各种不同的写法，你可以看 iOS 10.2 里，UIView.h 里的 `layer` 属性 和 `focused` 属性就是用不同的空格写法。
> 因此我们最终统一选择目前这种 property 和 ( 之间无空格的写法。

是的,苹果对规范这一点儿的确做的不够,不过您提到的在不同版本 SDK 中的写法不一致也算是不同时期的规范了.

**Comment by MoLice** [comment]
建议可以 fork 一份再自己调整，这个仓库只会新增，基本不会修改已有的代码片段，适合 fork。
