### ISSUE TITLE
xcode10.0 按照步骤操作 但是还是不行

### ISSUE THREAD

**Issue by dhhd917** [QMUI/QMUI_iOS_CodeSnippets#4]
如title算描述的

**Comment by MoLice** [comment]
尚未有其他人按照步骤操作后不生效的。请截图看看你的 ~/Library/Developer/Xcode/UserData/CodeSnippets 目录内容

**Comment by dhhd917** [comment]
![codesnippets](https://user-images.githubusercontent.com/27983702/47652436-e4956580-dbc0-11e8-8396-c6cee07e8819.png)

**Comment by MoLice** [comment]
CodeSnippet 不支持子目录，需要直接把 `*.codesnippet` 文件放到 CodeSnippets 内，而不是把 QMUI 的目录放到 CodeSnippets 目录内。我们在 README 里再强调一下这一点。
