### ISSUE TITLE
if使用的频率要高于ifos，是否将ifos再加一个前缀

### ISSUE THREAD

**Issue by xiky** [QMUI/QMUI_iOS_CodeSnippets#5]
你好，if使用的频率要高于ifos，是否将ifos再加一个前缀
日常开发中，ifos触发的频率太高了，自己fork了一份，修改为vifos，v表示version
这样是否更符合开发习惯

**Comment by xiky** [comment]
你好，if使用的频率要高于ifos，是否将ifos再加一个前缀
日常开发中，ifos触发的频率太高了，自己fork了一份，修改为vifos，v表示version
这样是否更符合开发习惯

**Comment by MoLice** [comment]
Xcode 会根据频率动态调整补全的顺序，所以这个问题只存在于前期。不过你这个思路可以，我们改为 `osif` 吧。

![image](https://user-images.githubusercontent.com/1190261/56113805-8b17cc00-5f91-11e9-91db-6f89a85830c6.png)

**Comment by MoLice** [comment]
https://github.com/QMUI/QMUI_iOS_CodeSnippets/commit/7e230d0d412c90f359dbda0d065ae8649df30f75
