### ISSUE TITLE
请问sharedInstance的红色框位置是否应该有空格?

### ISSUE THREAD

**Issue by yingkong1987** [QMUI/QMUI_iOS_CodeSnippets#6]
![image](https://user-images.githubusercontent.com/2038099/71802433-9ddead80-3098-11ea-9c20-f20d6467362c.png)

图一是我已经加了空格的. 图二是目前master上没加空格的.

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/2038099/71802496-cc5c8880-3098-11ea-91cc-344c73d81520.png">

根据平时日常阅读官方或者其他优秀开源代码的感觉看,应该是需要有空格的.

**Comment by MoLice** [comment]
可以，请提 pr

**Comment by yingkong1987** [comment]
> 可以，请提 pr

已经提交了PR. 大神回复真是神速! QMUI_iOS_CodeSnippets也大大提高了我们的开发效率.
